[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ingrid = "0.1.0"
partition = "0.1.2"
reqwest = {version = "0.11.7", features = ["blocking"]}
